image: "ruby:2.4"

before_script:
  - apt-get update -qq && apt-get install -y -qq redis-server memcached imagemagick libpq-dev inkscape rrdtool librrd8 librrd-dev git curl sqlite3 nodejs
  - ruby -v
  - which ruby
  - cp config/database.yml.gitlab config/database.yml
  - gem install bundler --no-ri --no-rdoc
  - bundle install --quiet
  - RAILS_ENV=test bundle exec rake db:create db:migrate --quiet
  - RAILS_ENV=test bundle exec rake db:test:prepare --quiet

minitest:
  script:
    - RAILS_ENV=test bundle exec rake test