image: "ruby:2.4"

services:
  - redis:latest
  - postgres:9.6

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/ruby

test:
  stage: test
  script:
    - apt-get update -qq && apt-get install -y -qq redis-server memcached imagemagick libpq-dev inkscape rrdtool librrd-dev git curl sqlite3 nodejs
    - ruby -v
    - which ruby
    - redis-cli -h redis PING
    - cp config/database.yml.gitlab config/database.yml
    - cp test/gitlab_redis.rb config/initializers/01_redis.rb
    - gem install bundler
    - bundle install -j $(nproc) --path vendor
    - RAILS_ENV=test bundle exec rake db:setup --quiet
    - RAILS_ENV=test bundle exec rake isk:secrets --quiet
    - RAILS_ENV=test bundle exec rake db:test:prepare --quiet
    - RAILS_ENV=test bundle exec rake test
  artifacts:
    paths:
      - coverage/